version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: guimel
      POSTGRES_USER: guimel
      POSTGRES_PASSWORD: guimel
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
